//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuotePad {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuotePad.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_64 {
            get {
                object obj = ResourceManager.GetObject("add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addPhoto_64 {
            get {
                object obj = ResourceManager.GetObject("addPhoto_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap apply_64 {
            get {
                object obj = ResourceManager.GetObject("apply_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap authorize_64 {
            get {
                object obj = ResourceManager.GetObject("authorize_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clearPhoto_64 {
            get {
                object obj = ResourceManager.GetObject("clearPhoto_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap createNew_64 {
            get {
                object obj = ResourceManager.GetObject("createNew_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_64 {
            get {
                object obj = ResourceManager.GetObject("delete_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_64 {
            get {
                object obj = ResourceManager.GetObject("edit_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favorite64 {
            get {
                object obj = ResourceManager.GetObject("favorite64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset204 Trebuchet MS;}{\f1\fswiss\fprq2\fcharset0 Trebuchet MS;}{\f2\fswiss\fcharset204{\*\fname Arial;}Arial CYR;}}
        ///{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs24\par
        ///\b\&apos;d7\&apos;f2\&apos;ee \&apos;f2\&apos;e0\&apos;ea\&apos;ee\&apos;e5 &quot;\&apos;d6\&apos;e8\&apos;f2\&apos;e0\&apos;f2\&apos;ed\&apos;e8\&apos;ea&quot;?\b0\par
        ///\&apos;d6\&apos;e8\&apos;f2\&apos;e0\&apos;f2\&apos;ed\&apos;e8\&apos;ea - \&apos;fd\&apos;f2\&apos;ee \&apos;f1\&apos;e2\&apos;ee\&apos;e1\&apos;ee\&apos;e4\&apos;ed\&apos;ee \&apos;f0\&apos;e0\&apos;f1\&apos;ef\&apos;f0\&apos;ee\&apos;f1\&apos;f2\&apos;f0\&apos;e0\&apos;ed\&apos;ff\&apos;e5\&apos;ec\&apos;e0\&apos;ff \&apos;ef\&apos;f0\&apos;ee\&apos;e3\&apos;f0\&apos;e0\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap next_64 {
            get {
                object obj = ResourceManager.GetObject("next_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap noPhoto_128 {
            get {
                object obj = ResourceManager.GetObject("noPhoto_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap previous_64 {
            get {
                object obj = ResourceManager.GetObject("previous_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap random_64 {
            get {
                object obj = ResourceManager.GetObject("random_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stars {
            get {
                object obj = ResourceManager.GetObject("stars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream starwars {
            get {
                return ResourceManager.GetStream("starwars", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap viewQuotes_64 {
            get {
                object obj = ResourceManager.GetObject("viewQuotes_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
