CREATE TABLE tAUTHORS (
	pID COUNTER
	    CONSTRAINT pkTYPE PRIMARY KEY,
	pNAME CHAR(50) NOT NULL,
	pINFO MEMO,
	pPHOTO IMAGE
)

CREATE TABLE tTHEMES (
	pID COUNTER
	    CONSTRAINT pkTYPE PRIMARY KEY,
	pNAME TEXT(15) NOT NULL
)

CREATE TABLE tQUOTES (
	pID COUNTER PRIMARY KEY,
	pAUTHOR INT NOT NULL
	        CONSTRAINT fktAUTHORS REFERENCES tAUTHORS(pID),
	pTHEME INT NOT NULL
	        CONSTRAINT fktTHEMES REFERENCES tTHEMES(pID),
	pQUOTE MEMO NOT NULL,
	pDT DATETIME NOT NULL
)